### ISSUE TITLE
配布されているapkが動きません

### ISSUE THREAD

**Issue by Yu-Saito** [EXILIM-Plugin/EXILIM-Plugin#1]
配布されているＡｎｄｒｏｉｄ用のapkをAndroid 5.1及び7.1.1の端末にインストールして試しましたが、動画表示その他が動作しません。　ボタンクリックで無反応ももしくはCONNECTION REFUSEDのエラーになってしまいます。

確認されているAndroidのバージョンはいくつでしょうか？

また、確認された端末を公開いただけませんか？

よろしくお願いします。

**Comment by casio-takuya-yamada** [comment]
対応Androidバージョン4.4以降となっております。
ただいま手元では下記の環境で動作確認しました。
端末：Nexus9 Ver.6.0.1
Device Web API Manager Ver.2.3.0
カメラ：G'z Eye
アプリ：exilimplugin.apk, sample.apk

確認手順は以下の通りです。
1.Device Web API Managerを起動し、設定の"Origin有効化"のチェックを外す
2.Device Web API Managerを"オン"にする
3.EXILIM Sample(sample.apk)を起動
4."PLUGIN SETUP"ボタンを押し、エラーが表示されないことを確認
5."LIVEVIEW START"ボタンを押しライブビュー画像が表示されることを確認
6."TAKE PHOTO"ボタンを押し、カメラが撮影を行なったことを確認

以上です。

**Comment by Yu-Saito** [comment]
sample.apkの動作を確認できました。
CONNECTION REFUSEDは別のAndroid端末とペアリングしていたカメラ側の設定をクリヤして動きました。

ありがとうございました。

**Comment by casio-takuya-yamada** [comment]
無事動いたようで安心しました。
また何かありましたらご連絡ください。
