### ISSUE TITLE
ストリームの動画フォーマット

### ISSUE THREAD

**Issue by Yu-Saito** [EXILIM-Plugin/EXILIM-Plugin#3]
exilimpluginから送信されるpreviewの動画フォーマットは何でしょうか？
更に、Device Web APIは動画のフォーマット変換無しでアプリ(sample.apk）へプッシュ送信してますか？

機器によりWebViewがサポートしていない動画フォーマットが考えられますので確認させてください。

よろしくお願いします。

**Comment by casio-takuya-yamada** [comment]
MotionJpegです。
Content-Type: multipart/x-mixed-replace にて、
フレームごとにJpegをプッシュ送信しています

**Comment by Yu-Saito** [comment]
フォーマットの情報ありがとうございます。
