### ISSUE TITLE
EX-FR100がWebAPI経由でPush送信するPreviewの画像サイズは？

### ISSUE THREAD

**Issue by Yu-Saito** [EXILIM-Plugin/EXILIM-Plugin#5]
Saitoです。
Web API がアプリにPush送信するPreviewの画像サイズはカメラの仕様に依存してますか？

EX-FR100の場合の画像サイズはいくらになりますか？
こちらのアプリでは３００ｘ２２５に見えますが、正しいですか？

これより大きいサイズ例えば６４０ｘ４００（ＶＧＡ）以上を取得する手段は有りますか？

アプリでVGAサイズ以上の動画ストリームを使用する事が好ましいので、よろしくお願いします。

**Comment by casio-takuya-yamada** [comment]
カメラの仕様に依存しています。
FR100では320×240(QVGA)となります。

カメラのファームウェアの設定でサイズは固定されているため、
操作用のアプリやプラグインからの変更はできません。

**Comment by Yu-Saito** [comment]
情報ありがとうございました。
